spring:
  application:
    name: produto-service
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: true

server:
  port: 8080

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
