spring:
  datasource:
    username: postgres
    password: aluno
    url: jdbc:postgresql://localhost:5432/usuarios_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
