spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:aluno}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/usuarios_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
