spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765

secret-key: ${SECRET_KEY:mySecretKey}
secret-access: ${SECRET_ACCESS_MICROSERVICES:secret-access-microservice}