INSERT INTO tb_products (barcode, name, description, price, stock_quantity, category, created_at, updated_at) VALUES
                                                                                                                  (987654, 'Smartphone Samsung Galaxy S21', 'Smartphone Samsung Galaxy S21 com 128GB, tela de 6.2 polegadas, câmera de 64MP.', 4999.99, 50, 'Eletrônicos', NOW(), NOW()),
                                                                                                                  (123456, 'Notebook Dell Inspiron 15', 'Notebook Dell Inspiron 15 com processador Intel i7, 8GB RAM e 512GB SSD.', 3499.00, 30, 'Eletrônicos', NOW(), NOW()),
                                                                                                                  (234567, 'Fone de Ouvido Sony WH-1000XM4', 'Fone de ouvido Sony com cancelamento de ruído, bateria de até 30 horas de reprodução.', 1799.99, 100, 'Áudio', NOW(), NOW()),
                                                                                                                  (345678, 'Camiseta Nike Dry-FIT', 'Camiseta de futebol Nike Dry-FIT, material respirável, disponível em tamanhos M, L e XL.', 129.99, 200, 'Roupas', NOW(), NOW()),
                                                                                                                  (456789, 'Tênis Adidas Ultraboost 21', 'Tênis Adidas Ultraboost 21, conforto excepcional, ótima absorção de impacto e estabilidade.', 799.90, 75, 'Calçados', NOW(), NOW()),
                                                                                                                  (567890, 'Relógio Casio G-Shock', 'Relógio Casio G-Shock resistente à água até 200 metros, com cronômetro e timer.', 599.99, 40, 'Acessórios', NOW(), NOW()),
                                                                                                                  (678901, 'Cadeira Gamer DXRacer Formula', 'Cadeira gamer DXRacer Formula, com suporte lombar ajustável e encosto reclinável até 180 graus.', 1599.00, 60, 'Móveis', NOW(), NOW()),
                                                                                                                  (789012, 'Cafeteira Nespresso Vertuo', 'Cafeteira Nespresso Vertuo, com capacidade de 1.2L e opções de 5 tamanhos de café.', 1299.00, 80, 'Eletrodomésticos', NOW(), NOW());
