spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientes_db
    username: postgres
    password: aluno
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    user: postgres
    url: jdbc:postgresql://localhost:5432/clientes_db
    password: aluno
    enabled: true
    schemas: public