spring:
  application:
    name: cliente-service

  profiles:
    active: dev

  jpa:
    open-in-view: false

eureka:
  client:
    register-with-eureka: true
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

server:
  port: 8081