spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clientes_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:aluno}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    user: ${DB_USERNAME:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clientes_db}
    password: ${DB_PASSWORD:aluno}
    enabled: true
    schemas: public