spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pedidos_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:aluno}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: public
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pedidos_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:aluno}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
