spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos_db
    username: postgres
    password: aluno
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: public
    url: jdbc:postgresql://localhost:5432/pedidos_db
    user: postgres
    password: aluno

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
